"""Type stubs for code_block module."""

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class LanguageType(str, Enum):
    JAVASCRIPT = ...
    TYPESCRIPT = ...
    PYTHON = ...
    JAVA = ...
    GO = ...
    RUST = ...
    C = ...
    CPP = ...
    CSHARP = ...
    PHP = ...
    RUBY = ...


class SemanticCategory(str, Enum):
    UTILITY = ...
    HELPER = ...
    VALIDATOR = ...
    API_HANDLER = ...
    AUTH_CHECK = ...
    DATABASE_OPERATION = ...
    ERROR_HANDLER = ...
    LOGGER = ...
    CONFIG_ACCESS = ...
    FILE_OPERATION = ...
    ASYNC_PATTERN = ...
    UNKNOWN = ...


class SourceLocation(BaseModel):
    file_path: str
    line_start: int
    line_end: int
    column_start: Optional[int]
    column_end: Optional[int]

    def __str__(self) -> str: ...


class ASTNode(BaseModel):
    node_type: str
    children: List[ASTNode]
    properties: Dict[str, Any]


class CodeBlock(BaseModel):
    block_id: str
    pattern_id: str
    location: SourceLocation
    relative_path: str
    source_code: str
    normalized_code: Optional[str]
    ast_structure: Optional[ASTNode]
    ast_hash: Optional[str]
    language: LanguageType
    category: SemanticCategory
    tags: List[str]
    match_context: Dict[str, Any]
    repository_path: str
    repository_name: Optional[str]
    git_commit: Optional[str]
    detected_at: datetime
    line_count: int
    complexity_score: Optional[float]

    @property
    def content_hash(self) -> str: ...
    @property
    def structural_hash(self) -> str: ...

    def to_dict_for_comparison(self) -> Dict[str, Any]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
