"""Type stubs for structural similarity module."""

from dataclasses import dataclass
from typing import Set, Tuple


@dataclass
class SemanticFeatures:
    """Semantic features extracted from original code before normalization."""
    http_status_codes: Set[int]
    logical_operators: Set[str]
    semantic_methods: Set[str]


def extract_semantic_features(source_code: str) -> SemanticFeatures: ...
def normalize_code(source_code: str) -> str: ...
def calculate_ast_hash(source_code: str) -> str: ...
def calculate_levenshtein_similarity(str1: str, str2: str) -> float: ...
def extract_logical_operators(source_code: str) -> set: ...
def extract_http_status_codes(source_code: str) -> set: ...
def extract_semantic_methods(source_code: str) -> set: ...
def extract_method_chain(source_code: str) -> list: ...
def compare_method_chains(code1: str, code2: str) -> float: ...
def calculate_semantic_penalty(
    features1: SemanticFeatures, features2: SemanticFeatures
) -> float: ...
def calculate_structural_similarity(
    code1: str, code2: str, threshold: float = ...
) -> Tuple[float, str]: ...
def are_structurally_similar(
    code1: str, code2: str, threshold: float = ...
) -> bool: ...
